name: Build Windows Executables

on:
  push:
    branches: [ main, fix-page-and-refactor ]
  pull_request:
    branches: [ main, fix-page-and-refactor ]
  workflow_dispatch:
    # Permette di eseguire manualmente il workflow dalla UI di GitHub

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build executables with PyInstaller
      run: |
        pyinstaller --onefile --windowed --add-data "data/logo.png;." --hidden-import report_utils --version-file version_info.txt --name generate_report_batch generate_report_batch.py
        pyinstaller --onefile --windowed --add-data "data/logo.png;." --hidden-import report_utils --version-file version_info.txt --name generate_report_alarm generate_report_alarm.py
        pyinstaller --onefile --windowed --add-data "data/logo.png;." --hidden-import report_utils --version-file version_info.txt --name generate_report_operlog generate_report_operlog.py
        pyinstaller --onefile --windowed --version-file version_info.txt --uac-admin --clean --name print_latest_pdf print_latest_pdf.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-executables-${{ github.ref_name }}
        path: dist/*.exe
    
    - name: Display build info
      run: |
        echo "✅ Build completed for branch: ${{ github.ref_name }}"
        echo "📦 Executables built with:"
        echo "  - Fixed page numbering (1/2, 2/2 instead of 1/1, 2/1)"
        echo "  - Shared report_utils.py module for better code maintainability"
        echo "  - All original functionality preserved"
        echo "  - All executables now include version info and company metadata for better antivirus compatibility"
        dir dist